// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_q90AJecCB7cy260MhbV09yK_uoZV4tk',
    appId: '1:149971017649:web:e2e6009242f66276972790',
    messagingSenderId: '149971017649',
    projectId: 'elrapidoinv-c3df4',
    authDomain: 'elrapidoinv-c3df4.firebaseapp.com',
    storageBucket: 'elrapidoinv-c3df4.firebasestorage.app',
    measurementId: 'G-LZCRX94D5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRFtJ-QixJJKY4bIdZotubpsBR7eIBGw4',
    appId: '1:149971017649:android:092022e76be8643b972790',
    messagingSenderId: '149971017649',
    projectId: 'elrapidoinv-c3df4',
    storageBucket: 'elrapidoinv-c3df4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbm81E70ke8Z0nuP4W5w-47_mOgkFARNc',
    appId: '1:149971017649:ios:9bbf45c87ca7b29f972790',
    messagingSenderId: '149971017649',
    projectId: 'elrapidoinv-c3df4',
    storageBucket: 'elrapidoinv-c3df4.firebasestorage.app',
    iosBundleId: 'com.example.elRapidoInc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbm81E70ke8Z0nuP4W5w-47_mOgkFARNc',
    appId: '1:149971017649:ios:9bbf45c87ca7b29f972790',
    messagingSenderId: '149971017649',
    projectId: 'elrapidoinv-c3df4',
    storageBucket: 'elrapidoinv-c3df4.firebasestorage.app',
    iosBundleId: 'com.example.elRapidoInc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_q90AJecCB7cy260MhbV09yK_uoZV4tk',
    appId: '1:149971017649:web:71057ded14271026972790',
    messagingSenderId: '149971017649',
    projectId: 'elrapidoinv-c3df4',
    authDomain: 'elrapidoinv-c3df4.firebaseapp.com',
    storageBucket: 'elrapidoinv-c3df4.firebasestorage.app',
    measurementId: 'G-2G9LCXK5JN',
  );
}
