name: Flutter Test

on:
  push:
    branches:
      - main # or the branch you want to run tests on
  pull_request:
    branches:
      - main # or the branch you want to run tests on

jobs:
  flutter-test:
    runs-on: ubuntu-latest # You can also use macos-latest if you want to test on macOS

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # or specify a specific version

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
