name: Flutter Test

on:
  push:
    branches:
      - main  # or the branch you want to run tests on
  pull_request:
    branches:
      - main  # or the branch you want to run tests on

jobs:
  flutter-test:
    runs-on: ubuntu-latest  # You can also use macos-latest if you want to test on macOS

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            flutter-version: '3.24.5'  # or specify a specific version

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .flutter-plugins
            .packages
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --platform chrome  # Run tests on Chrome
      
      - name: Build web
        run: flutter build web

      - name: Check available secrets
        run: echo "FIREBASE_SERVICE_ACCOUNT=${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" || echo "Secret not found"  

  # Trigger the deploy workflow only if the tests pass
  deploy:
    needs: flutter-test  # This ensures deployment only happens if tests succeed
    uses: ./.github/workflows/deploy_to_firebase.yml  # Calls the deployment workflow
