name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main  # Specify the branches to trigger this workflow
  pull_request:
    branches:
      - main

jobs:
  flutter-test:
    runs-on: ubuntu-latest  # You can change to macos-latest for macOS
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .flutter-plugins
            .packages
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test --platform chrome

      - name: Build for web
        run: flutter build web

      - name: Validate Firebase secret
        run: echo "FIREBASE_SERVICE_ACCOUNT=${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" || echo "Secret not found"

  deploy:
    needs: flutter-test  # Ensures this job runs only if the test job succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ELRAPIDOINV_C3DF4 }}'
          channelId: live
          projectId: elrapidoinv-c3df4
